# Generated by Django 4.1.4 on 2022-12-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='descript',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
    ]
