# Generated by Django 4.1.4 on 2022-12-21 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_item_descript'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='descript',
            new_name='description',
        ),
    ]
