# Generated by Django 3.2 on 2023-01-10 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_auto_20230110_0637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='recived',
            new_name='received',
        ),
    ]
